name: async_phase_notifier
description: A ValueNotifier that helps you better manage phases of async operations.
version: 0.0.1
repository: https://github.com/kaboc/async-phase-notifier

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.7.0

dev_dependencies:
  flutter_lints: ^2.0.1
