name: async_phase_notifier CI

on:
  push:
    paths:
      - 'packages/async_phase_notifier/**'
      - '.github/workflows/async_phase_notifier.yaml'
    tags:
      - '*'
  pull_request:
    branches: [main]
    paths:
      - 'packages/async_phase_notifier/**'
      - '.github/workflows/async_phase_notifier.yaml'
  workflow_dispatch:

jobs:
  async_phase_notifier_ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/async_phase_notifier
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.10.0
      - name: Install dependencies
        run: flutter pub get
      - name: Check format
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze
        run: flutter analyze --no-pub
      - name: Run tests
        run: flutter test
